version: '3.8'

services:
  app:
    image: matiasbasile/varcreative
    container_name: inmovar-app
    restart: always
    working_dir: /var/www/
    environment:
      - DATABASE=${DATABASE}
      - PASSWORD_DB=${PASSWORD_DB}
      - SERVER_DB=${SERVER_DB}
      - PROJECT_NAME=${PROJECT_NAME}
      - COLOR_1=${COLOR_1}
      - LOGO=${LOGO}
      - LOGO_LOGIN=${LOGO_LOGIN}
      - CSS_LOGIN=${CSS_LOGIN}
      - MANTENIMIENTO=${MANTENIMIENTO}
    volumes:
      - .:/var/www

  nginx:
    image: matiasbasile/nginx
    container_name: inmovar-nginx
    restart: always
    ports:
      - ${NGINX_PORT}:80
    volumes:
      - .:/var/www
      - ./docker/inmovar:/etc/nginx/conf.d/
    environment:
      - SERVER_DB:"inmovar-mysql"

  mysql:
    #image: matiasbasile/mysql
    image: mariadb:11
    restart: always
    container_name: inmovar-mysql
    command: mariadbd --sql_mode=""
    environment:
      - MYSQL_ROOT_PASSWORD=${PASSWORD_DB}
      - MYSQL_DATABASE=${DATABASE}
    volumes:
      - inmovar-data:/var/lib/mysql

volumes:
  inmovar-data:

networks: 
  default: 
    external: 
      name: varcreative-network